
name: AWS Lambda Deploy
on:
  push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: zip -r upload.zip *
      - uses: stcalica/update-lambda
        with: 
          package: upload.zip
          function-name: batchJunRemind
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
