
name: AWS Lambda Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: zip -r upload.zip *
      - uses: yvesgurcan/deploy-lambda-function
        with: 
          package: upload.zip
          function-name: deploy-test
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
