
name: AWS Lambda Deploy
on:
  push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-go@v2
      - name: Dependencies
        run: go get -v
      - name: Build
        run: go build .
      - name: Zip
        run: zip -r upload.zip jrb
      - name: Deploy
        uses: stcalica/update-lambda@master
        with: 
          package: upload.zip
          function-name: batch_jun_remind
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
